# Generated by Django 5.1.4 on 2025-02-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineitem",
            name="is_truffled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderlineitem",
            name="quantity_kilo",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
