# Generated by Django 5.1.4 on 2025-02-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_orderlineitem_is_truffled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_bag",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254),
        ),
    ]
