# Generated by Django 3.2.25 on 2024-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storeupdate',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
