# Generated by Django 5.1.4 on 2025-03-06 13:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20241203_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeupdate",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="noimage.jpg",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
