# Generated by Django 5.1.4 on 2025-07-14 20:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimonies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimony",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/dx21s72fa/image/upload/v1727857392/w0wngka886ke3rcyr5gd.png",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
