# Generated by Django 5.1.4 on 2024-12-11 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Flavor")),
            ],
            options={
                "verbose_name": "Flavor",
                "verbose_name_plural": "Flavors",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "custom_title",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Custom Title",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sale_option",
                    models.CharField(
                        choices=[
                            ("unit", "Per Unit"),
                            ("hundred", "Per Hundred"),
                            ("kilo", "Per Kilo"),
                            ("piece", "Per Piece"),
                            ("size", "By Size (Small, Medium, Large)"),
                        ],
                        default="unit",
                        max_length=20,
                        verbose_name="Sale Option",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Size",
                    ),
                ),
                (
                    "shipping_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Shipping Information"
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("is_best_seller", models.BooleanField(default=False)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                (
                    "flavors",
                    models.ManyToManyField(
                        blank=True, to="products.flavor", verbose_name="Flavors"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Comment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
