# Generated by Django 5.1.4 on 2024-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_friendly_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavor",
            name="is_truffled",
            field=models.BooleanField(default=False, verbose_name="Is Truffled"),
        ),
    ]
