# Generated by Django 5.1.4 on 2024-12-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_flavor_is_truffled"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_roses",
            field=models.BooleanField(default=False, verbose_name="Has Roses"),
        ),
        migrations.AddField(
            model_name="product",
            name="has_topper",
            field=models.BooleanField(default=False, verbose_name="Has Topper"),
        ),
    ]
