# Generated by Django 3.2.25 on 2024-12-10 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20241209_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='custom_title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Custom Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_option',
            field=models.CharField(choices=[('unit', 'Per Unit'), ('hundred', 'Per Hundred'), ('kilo', 'Per Kilo'), ('piece', 'Per Piece'), ('size', 'By Size (Small, Medium, Large)')], default='unit', max_length=20, verbose_name='Sale Option'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.TextField(blank=True, null=True, verbose_name='Shipping Information'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
