# Generated by Django 5.1.4 on 2024-12-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20241210_0955"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="friendly_name_en",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="friendly_name_pt_br",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_pt_br",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_title_en",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Custom Title"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_title_pt_br",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Custom Title"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_pt_br",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_pt_br",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_info_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Shipping Information"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_info_pt_br",
            field=models.TextField(
                blank=True, null=True, verbose_name="Shipping Information"
            ),
        ),
    ]
