# Generated by Django 5.1.4 on 2024-12-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_friendly_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_pt_br",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
