# Generated by Django 5.1.4 on 2025-02-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_flavor_name_alter_flavor_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavor",
            name="name",
            field=models.CharField(max_length=254, unique=True, verbose_name="Flavor"),
        ),
        migrations.AlterField(
            model_name="flavor",
            name="name_en",
            field=models.CharField(
                max_length=254, null=True, unique=True, verbose_name="Flavor"
            ),
        ),
        migrations.AlterField(
            model_name="flavor",
            name="name_pt_br",
            field=models.CharField(
                max_length=254, null=True, unique=True, verbose_name="Flavor"
            ),
        ),
    ]
