# Generated by Django 5.1.4 on 2025-02-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_flavor_name_alter_flavor_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavor",
            name="name",
            field=models.CharField(max_length=254, verbose_name="Flavor"),
        ),
        migrations.AlterField(
            model_name="flavor",
            name="name_en",
            field=models.CharField(max_length=254, null=True, verbose_name="Flavor"),
        ),
        migrations.AlterField(
            model_name="flavor",
            name="name_pt_br",
            field=models.CharField(max_length=254, null=True, verbose_name="Flavor"),
        ),
    ]
