# Generated by Django 5.1.4 on 2024-12-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_name_alter_product_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="small",
                max_length=20,
                verbose_name="Size",
            ),
        ),
    ]
