# Generated by Django 5.1.4 on 2025-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_flavor_name_alter_flavor_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="flavors",
            field=models.ManyToManyField(to="products.flavor", verbose_name="Flavors"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="Unnamed Product", max_length=254),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                default="Unnamed Product", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_pt_br",
            field=models.CharField(
                default="Unnamed Product", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_info",
            field=models.TextField(blank=True, default="Shipping information "),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_info_en",
            field=models.TextField(
                blank=True, default="Shipping information ", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_info_pt_br",
            field=models.TextField(
                blank=True, default="Shipping information ", null=True
            ),
        ),
    ]
