# Generated by Django 5.1.4 on 2024-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_price_alter_product_size_flavor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavor",
            name="name_en",
            field=models.CharField(max_length=254, null=True, verbose_name="Flavor"),
        ),
        migrations.AddField(
            model_name="flavor",
            name="name_pt_br",
            field=models.CharField(max_length=254, null=True, verbose_name="Flavor"),
        ),
    ]
