# Generated by Django 5.1.4 on 2025-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_name_alter_product_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_option",
            field=models.CharField(
                choices=[
                    ("unit", "Per Unit"),
                    ("hundred", "Per Hundred"),
                    ("kilo", "Per Kilo"),
                    ("piece", "Per Piece"),
                    ("size", "By Size (Small, Medium, Large)"),
                ],
                max_length=20,
                verbose_name="Sale Option",
            ),
        ),
    ]
