# Generated by Django 5.1.4 on 2025-03-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_price_alter_product_sale_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="noimage.jpg", null=True, upload_to=""
            ),
        ),
    ]
