# Generated by Django 5.1.4 on 2025-09-06 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_personalizedcakeorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalizedcakeorder",
            name="message",
        ),
        migrations.RemoveField(
            model_name="personalizedcakeorder",
            name="product",
        ),
        migrations.RemoveField(
            model_name="personalizedcakeorder",
            name="reference_image",
        ),
        migrations.RemoveField(
            model_name="personalizedcakeorder",
            name="size",
        ),
        migrations.AddField(
            model_name="personalizedcakeorder",
            name="quantity_kilo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="personalizedcakeorder",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="flavor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.flavor",
            ),
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="roses_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="topper_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
