# Generated by Django 5.1.4 on 2025-09-07 18:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_remove_personalizedcakeorder_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalizedcakeorder",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalizedcakeorder",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="cake_photo"
            ),
        ),
    ]
