# Generated by Django 5.1.4 on 2025-09-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_personalizedcakeorder_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="quantity_kilo",
            field=models.IntegerField(default=0),
        ),
    ]
