# Generated by Django 5.1.4 on 2025-10-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_alter_personalizedcakeorder_quantity_kilo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalizedcakeorder",
            options={},
        ),
        migrations.RemoveField(
            model_name="personalizedcakeorder",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="flavor",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cakes_photos/"),
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="quantity_kilo",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
