# Generated by Django 5.1.4 on 2025-11-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_alter_personalizedcakeorder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="flavor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.flavor"
            ),
        ),
    ]
