# Generated by Django 5.1.4 on 2025-11-06 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_alter_personalizedcakeorder_flavor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalizedcakeorder",
            name="flavor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.flavor",
            ),
        ),
    ]
